# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel" "dcdbas" "dell-smm-hwmon"];
  boot.extraModulePackages = with config.boot.kernelPackages; [v4l2loopback];
  # boot.extraModprobeConfig = ''    # found that in a related NixOS thread
  #    options snd-intel-dspcfg dsp_driver=1
  # '';
  boot.kernelParams = [
    # "threadirqs" # Helps offload interrupt processing
    # "scsi_mod.use_blk_mq=1"
    # "skew_tick=1" # Helps align timer interrupts to happen at the same timer
    #
    # "pcie_aspm.policy=powersave"
    # "workqueue.power_efficient=Y"
    # "x86_pkg_temp_thermal.enable=1"
    #
    # "intel_idle.max_cstate=10"
    # "acpi_rev_override=1" # Sometimes needed for modern standby
    #
    # # SSD Power Management
    # "nvme_core.default_ps_max_latency_us=0"
    # "pcie_aspm=force"
    # "port_pirq=disable"
    #
    # # iGPU
    # "i915.enable_dc=4" # Deep Link Power Management
    # "i915.enable_guc=3" # Use GuC/HuC firmware
    # "i915.enable_fbc=1" # Framebuffer compression
    # "i915.enable_psr=1" # Panel Self Refresh
    #
    # # Audio Power Management
    # "snd_hda_intel.power_save=1"
    # "snd_hda_intel.power_save_controller=y"
    #
    # example settings
    "quiet"
    "splash"
  ];
  boot.blacklistedKernelModules = [
    # Disable SD Reader
    "rtsx_pci_sdmmc"
    "rtsx_pci"

    # Disable Intel Telemetry Driver
    "intel_vsec"
    "intel_th"
    "intel_th_pci"

    "nouveau"
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/7db4a535-782a-46f5-941f-14598a03bbbf";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F041-3EFD";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s13f0u1u1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Includes the Wi-Fi and Bluetooth firmware
  hardware.enableRedistributableFirmware = true;

  services.fstrim.enable = lib.mkDefault true;
}
